services:

  app:
    build:
      context: .
    ports:
      - "8080:5000"
    volumes:
      - skylab:/var/lib/skylab
    networks:
      - public
      - private
    depends_on:
      - database

  database:
    image: postgres:17.4-alpine3.21
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=Empresa
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    networks:
      - private

volumes:
  skylab:
  db:

networks:
  public:
  private: