services:
  app:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - skylab_net
    restart: unless-stopped

  database:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: Empresa
      PGDATA: /var/lib/postgresql/data/pgdata  # Linha crucial adicionada
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d Empresa"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - skylab_net
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./postgres-data  # Armazena dados em um diretório físico
      o: bind

networks:
  skylab_net:
    driver: bridge