version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:5000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - skylab-net

  database:
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: Empresa
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - skylab-net

volumes:
  pg_data:

networks:
  skylab-net:
    driver: bridge